#!/usr/bin/env python3
"""Compile-time public source filenames only; never discover a user's files at runtime."""
from pathlib import Path
import argparse
root = Path(__file__).resolve().parents[1]
app = root / 'Sources/LocalHistoryApp'
out = app / 'SupportSourceAllowlist.swift'
names = sorted({p.name for p in app.rglob('*.swift')})
text = '// Generated by scripts/generate_support_source_allowlist.py. See docs/SUPPORT_DIAGNOSTICS.md.\n#if os(macOS)\nenum SupportSourceAllowlist {\n    static let names: Set<String> = [\n' + ''.join(f'        "{name}",\n' for name in names) + '    ]\n}\n#endif\n'
parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
if args.check:
    if out.read_text() != text:
        raise SystemExit('Support source allowlist is stale; run scripts/generate_support_source_allowlist.py')
else:
    out.write_text(text)
